### PR TITLE
changed api from toggl.com to api.track.toggl.com

### PR DESCRIPTION
**Pull request by FriesBoury**
The toggl Button for Azure Devops no longer works.
Explanation why can be found here:
https://support.toggl.com/en/articles/5708431-why-did-my-integration-stop-working

### CODE REVIEW

**Comment by bane676** [comment]
@GersonDias: Can this PR be merged? The extension is currently broken for everyone until this is done.

**Comment by GersonDias** [comment]
@bane676 thanks for the PR and sorry for a long time without response. I also deployed the new version of the extension and of the backend that supports it. Please let me know if it's working properly.

**Comment by FriesBoury** [comment]
> @bane676 thanks for the PR and sorry for a long time without response. I also deployed the new version of the extension and of the backend that supports it. Please let me know if it's working properly.

Thanks for the update, works like a charm!

**Comment by bane676** [comment]
Thanks @FriesBoury for submitting the PR and thanks @GersonDias for merging and publishing!  Works perfectly!

**Pull request merged**
